F tests/test_1.py::Tests1::()::test_1
 self = <tests.test_1.Tests1 instance at 0x105be55f0>
 
     def test_1(self):
         result = add_values(1,1)
 >       assert result == 2
 E       assert True == 2
 
 tests/test_1.py:8: AssertionError
F tests/test_1.py::Tests2::()::test_2
 self = <tests.test_1.Tests2 instance at 0x1065ebab8>
 
     def test_2(self):
         result = return3()
 >       assert result == 3
 E       assert 4 == 3
 
 tests/test_1.py:13: AssertionError
. tests/test_1.py::Tests2::()::test_3
